version: 3.8

services:
  postgres-todo:
    container_name: todo_db
    hostname: postgres-todo-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:changeme}
      POSTGRES_DB: ${POSTGRES_PASSWORD:todo_db}
    ports:
      - 5432:5432

  todo-api:
    container_name: todo_api
    hostname: todo-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    environment:
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST:postgres-todo-db}
      DB_PORT: ${DB_PORT:5432}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "${PORT}:${PORT}"
